In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
Fin_df = pd.DataFrame()

# Dataset Temperatura

In [2]:
ciudad = ['Armenia','Barranquilla','Bogota','Bucaramanga',
       'Cali','Cartagena','Cucuta','Florencia','Ibague',
       'Manizales','Medellin','Monteria','Neiva','Pasto',
       'Pereira','Popayan','Quibdo','Riohacha','Sanandres',
       'Santamarta','Sincelejo','Tunja','Valledupar',
          'Villavicencio']
ci = 23
dataset_dir = 'TEMPCSV/'+ ciudad[ci] +'.csv' #Se carga el dataset
df_temp = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual está separado por comas
df_temp['Ciudad'] = ciudad[ci]
df_temp.isnull().sum() #Se imprime el dataset

system:time_start      0
LST_Day_1km          702
Ciudad                 0
dtype: int64

In [3]:
df_temp

     system:time_start  LST_Day_1km         Ciudad
0         Dec 31, 2018       33.560  Villavicencio
1          Jan 1, 2019       25.110  Villavicencio
2          Jan 2, 2019       32.249  Villavicencio
3          Jan 3, 2019          NaN  Villavicencio
4          Jan 4, 2019       30.295  Villavicencio
...                ...          ...            ...
1091      Dec 26, 2021       27.778  Villavicencio
1092      Dec 27, 2021       22.670  Villavicencio
1093      Dec 28, 2021       24.454  Villavicencio
1094      Dec 29, 2021          NaN  Villavicencio
1095      Dec 30, 2021       31.296  Villavicencio

[1096 rows x 3 columns]

In [4]:
date = df_temp["system:time_start"].str.split('[ ,]', expand=True)
date.columns = ['Mes','dia','DEL','Ano']

df_temp = pd.concat([df_temp, date], axis=1)
del(df_temp['DEL'])
del(df_temp['system:time_start'])
del(df_temp['dia'])

df_temp

      LST_Day_1km         Ciudad  Mes   Ano
0          33.560  Villavicencio  Dec  2018
1          25.110  Villavicencio  Jan  2019
2          32.249  Villavicencio  Jan  2019
3             NaN  Villavicencio  Jan  2019
4          30.295  Villavicencio  Jan  2019
...           ...            ...  ...   ...
1091       27.778  Villavicencio  Dec  2021
1092       22.670  Villavicencio  Dec  2021
1093       24.454  Villavicencio  Dec  2021
1094          NaN  Villavicencio  Dec  2021
1095       31.296  Villavicencio  Dec  2021

[1096 rows x 4 columns]

In [5]:
df_agrup = df_temp.drop_duplicates(subset=['Mes','Ano'],keep='last', inplace=False) #Se borran todas las filas
#df_agrup['precipitation'] = 0
del(df_agrup['LST_Day_1km'])
df_agrupado = df_agrup.drop(df_agrup[df_agrup['Ano']=='2018'].index)
df_agrupado.reset_index(drop=True, inplace=True)#Se reinicia el index, con el fin de que el número de cada fila quede ordenado
df_agrupado

           Ciudad  Mes   Ano
0   Villavicencio  Jan  2019
1   Villavicencio  Feb  2019
2   Villavicencio  Mar  2019
3   Villavicencio  Apr  2019
4   Villavicencio  May  2019
5   Villavicencio  Jun  2019
6   Villavicencio  Jul  2019
7   Villavicencio  Aug  2019
8   Villavicencio  Sep  2019
9   Villavicencio  Oct  2019
10  Villavicencio  Nov  2019
11  Villavicencio  Dec  2019
12  Villavicencio  Jan  2020
13  Villavicencio  Feb  2020
14  Villavicencio  Mar  2020
15  Villavicencio  Apr  2020
16  Villavicencio  May  2020
17  Villavicencio  Jun  2020
18  Villavicencio  Jul  2020
19  Villavicencio  Aug  2020
20  Villavicencio  Sep  2020
21  Villavicencio  Oct  2020
22  Villavicencio  Nov  2020
23  Villavicencio  Dec  2020
24  Villavicencio  Jan  2021
25  Villavicencio  Feb  2021
26  Villavicencio  Mar  2021
27  Villavicencio  Apr  2021
28  Villavicencio  May  2021
29  Villavicencio  Jun  2021
30  Villavicencio  Jul  2021
31  Villavicencio  Aug  2021
32  Villavicencio  Sep  2021
33  Villavicencio  Oct  2021
34  Villavicencio  Nov  2021
35  Villavicencio  Dec  2021

In [6]:
df_temp = df_temp.drop(df_temp[df_temp['LST_Day_1km']==0].index)
df_temp.head(40)

    LST_Day_1km         Ciudad  Mes   Ano
0        33.560  Villavicencio  Dec  2018
1        25.110  Villavicencio  Jan  2019
2        32.249  Villavicencio  Jan  2019
3           NaN  Villavicencio  Jan  2019
4        30.295  Villavicencio  Jan  2019
5        29.658  Villavicencio  Jan  2019
6        31.912  Villavicencio  Jan  2019
7        28.800  Villavicencio  Jan  2019
8           NaN  Villavicencio  Jan  2019
9        31.557  Villavicencio  Jan  2019
10          NaN  Villavicencio  Jan  2019
11          NaN  Villavicencio  Jan  2019
12          NaN  Villavicencio  Jan  2019
13          NaN  Villavicencio  Jan  2019
14       33.678  Villavicencio  Jan  2019
15          NaN  Villavicencio  Jan  2019
16       34.248  Villavicencio  Jan  2019
17          NaN  Villavicencio  Jan  2019
18          NaN  Villavicencio  Jan  2019
19          NaN  Villavicencio  Jan  2019
20          NaN  Villavicencio  Jan  2019
21       23.388  Villavicencio  Jan  2019
22          NaN  Villavicencio  Jan  2019
23       34.596  Villavicencio  Jan  2019
24          NaN  Villavicencio  Jan  2019
25       32.065  Villavicencio  Jan  2019
26          NaN  Villavicencio  Jan  2019
27          NaN  Villavicencio  Jan  2019
28       34.071  Villavicencio  Jan  2019
29          NaN  Villavicencio  Jan  2019
30        9.126  Villavicencio  Jan  2019
31          NaN  Villavicencio  Jan  2019
32       35.151  Villavicencio  Feb  2019
33       11.130  Villavicencio  Feb  2019
34       34.761  Villavicencio  Feb  2019
35          NaN  Villavicencio  Feb  2019
36          NaN  Villavicencio  Feb  2019
37          NaN  Villavicencio  Feb  2019
38          NaN  Villavicencio  Feb  2019
39       33.506  Villavicencio  Feb  2019

In [7]:
#dato_list = [ (0, 'Jan', 2019 ),(0, 'Feb', 2019 )]
#dfNew=pd.DataFrame(dato_list, columns = ['precipitation' , 'Mes', 'Ano'])
#df_pre=dfNew.append(df_pre,ignore_index=True)

In [8]:
df_agrup = df_temp.drop_duplicates(subset=['Mes','Ano'],keep='last', inplace=False) #Se borran todas las filas
#df_agrup['precipitation'] = np.zeros()
df_agrup.reset_index(drop=True, inplace=True)#Se reinicia el index, con el fin de que el número de cada fila quede ordenado
df_agrup

    LST_Day_1km         Ciudad  Mes   Ano
0        33.560  Villavicencio  Dec  2018
1           NaN  Villavicencio  Jan  2019
2        35.411  Villavicencio  Feb  2019
3           NaN  Villavicencio  Mar  2019
4           NaN  Villavicencio  Apr  2019
5        27.318  Villavicencio  May  2019
6           NaN  Villavicencio  Jun  2019
7           NaN  Villavicencio  Jul  2019
8           NaN  Villavicencio  Aug  2019
9        17.570  Villavicencio  Sep  2019
10          NaN  Villavicencio  Oct  2019
11       25.895  Villavicencio  Nov  2019
12       29.956  Villavicencio  Dec  2019
13       28.644  Villavicencio  Jan  2020
14       32.518  Villavicencio  Feb  2020
15          NaN  Villavicencio  Mar  2020
16          NaN  Villavicencio  Apr  2020
17          NaN  Villavicencio  May  2020
18       24.426  Villavicencio  Jun  2020
19       24.527  Villavicencio  Jul  2020
20          NaN  Villavicencio  Aug  2020
21          NaN  Villavicencio  Sep  2020
22          NaN  Villavicencio  Oct  2020
23       21.137  Villavicencio  Nov  2020
24          NaN  Villavicencio  Dec  2020
25       30.689  Villavicencio  Jan  2021
26          NaN  Villavicencio  Feb  2021
27          NaN  Villavicencio  Mar  2021
28          NaN  Villavicencio  Apr  2021
29          NaN  Villavicencio  May  2021
30          NaN  Villavicencio  Jun  2021
31          NaN  Villavicencio  Jul  2021
32       12.628  Villavicencio  Aug  2021
33          NaN  Villavicencio  Sep  2021
34          NaN  Villavicencio  Oct  2021
35          NaN  Villavicencio  Nov  2021
36       31.296  Villavicencio  Dec  2021

In [9]:
df_agrup = df_agrupado.merge(df_agrup, on=["Mes","Ano",'Ciudad'], how="left").fillna(0)
df_agrup

           Ciudad  Mes   Ano  LST_Day_1km
0   Villavicencio  Jan  2019        0.000
1   Villavicencio  Feb  2019       35.411
2   Villavicencio  Mar  2019        0.000
3   Villavicencio  Apr  2019        0.000
4   Villavicencio  May  2019       27.318
5   Villavicencio  Jun  2019        0.000
6   Villavicencio  Jul  2019        0.000
7   Villavicencio  Aug  2019        0.000
8   Villavicencio  Sep  2019       17.570
9   Villavicencio  Oct  2019        0.000
10  Villavicencio  Nov  2019       25.895
11  Villavicencio  Dec  2019       29.956
12  Villavicencio  Jan  2020       28.644
13  Villavicencio  Feb  2020       32.518
14  Villavicencio  Mar  2020        0.000
15  Villavicencio  Apr  2020        0.000
16  Villavicencio  May  2020        0.000
17  Villavicencio  Jun  2020       24.426
18  Villavicencio  Jul  2020       24.527
19  Villavicencio  Aug  2020        0.000
20  Villavicencio  Sep  2020        0.000
21  Villavicencio  Oct  2020        0.000
22  Villavicencio  Nov  2020       21.137
23  Villavicencio  Dec  2020        0.000
24  Villavicencio  Jan  2021       30.689
25  Villavicencio  Feb  2021        0.000
26  Villavicencio  Mar  2021        0.000
27  Villavicencio  Apr  2021        0.000
28  Villavicencio  May  2021        0.000
29  Villavicencio  Jun  2021        0.000
30  Villavicencio  Jul  2021        0.000
31  Villavicencio  Aug  2021       12.628
32  Villavicencio  Sep  2021        0.000
33  Villavicencio  Oct  2021        0.000
34  Villavicencio  Nov  2021        0.000
35  Villavicencio  Dec  2021       31.296

In [10]:
val_mes = df_agrup['Mes'] #Se guardan los valores de la columna 
val_ano = df_agrup['Ano'] #Se guardan los valores de la columna 

vect_a = [] #Se crea un vector vacío
vect_b = [] #Se crea un vector vacío
vect_c = [] #Se crea un vector vacío
vect_d = [] #Se crea un vector vacío

for n_Mes,n_Ano in zip(val_mes,val_ano): 
    vect_a.append(df_temp.loc[(df_temp['Mes'] == n_Mes) & (df_temp['Ano'] == n_Ano) ,'LST_Day_1km'].mean())


df_agrup['LST_Day_1km'] = vect_a

df_agrup

           Ciudad  Mes   Ano  LST_Day_1km
0   Villavicencio  Jan  2019    29.339500
1   Villavicencio  Feb  2019    32.384400
2   Villavicencio  Mar  2019    31.920500
3   Villavicencio  Apr  2019    26.833333
4   Villavicencio  May  2019    26.960333
5   Villavicencio  Jun  2019    24.203857
6   Villavicencio  Jul  2019    24.045111
7   Villavicencio  Aug  2019    27.756500
8   Villavicencio  Sep  2019    27.081643
9   Villavicencio  Oct  2019    28.451667
10  Villavicencio  Nov  2019    25.791800
11  Villavicencio  Dec  2019    28.196462
12  Villavicencio  Jan  2020    29.483000
13  Villavicencio  Feb  2020    32.608687
14  Villavicencio  Mar  2020    24.564357
15  Villavicencio  Apr  2020    27.535375
16  Villavicencio  May  2020    24.456000
17  Villavicencio  Jun  2020    25.695667
18  Villavicencio  Jul  2020    25.935250
19  Villavicencio  Aug  2020    24.785900
20  Villavicencio  Sep  2020    26.674308
21  Villavicencio  Oct  2020    27.817000
22  Villavicencio  Nov  2020    21.506538
23  Villavicencio  Dec  2020    28.404133
24  Villavicencio  Jan  2021    28.209647
25  Villavicencio  Feb  2021    29.647714
26  Villavicencio  Mar  2021    27.884000
27  Villavicencio  Apr  2021    27.108250
28  Villavicencio  May  2021    19.750571
29  Villavicencio  Jun  2021    21.755364
30  Villavicencio  Jul  2021    23.975000
31  Villavicencio  Aug  2021    21.975500
32  Villavicencio  Sep  2021    26.254917
33  Villavicencio  Oct  2021    26.625500
34  Villavicencio  Nov  2021    26.822733
35  Villavicencio  Dec  2021    28.734438

In [11]:
vect_tri = []
df_agr = pd.DataFrame()
df_agr['Temperatura1'] = None
c = [0,3,6,9,12,15,18,21,24,27,30,33,36,39]
i = 0
for n in df_agrup['Mes'].index:
    #print(c[i],n)
    vect_tri.append(df_agrup.loc[(df_agrup['Mes'].index >= c[i]) & (df_agrup['Mes'].index < c[i+1]),'LST_Day_1km'].mean())
    if n == c[i]:
        i = 1+i
df_agr['Temperatura1'] = vect_tri
df_agr = df_agr
df_agr

    Temperatura1
0      31.214800
1      25.999175
2      25.999175
3      25.999175
4      26.294418
5      26.294418
6      26.294418
7      27.479976
8      27.479976
9      27.479976
10     28.885348
11     28.885348
12     28.885348
13     25.895681
14     25.895681
15     25.895681
16     25.798486
17     25.798486
18     25.798486
19     25.909224
20     25.909224
21     25.909224
22     28.580454
23     28.580454
24     28.580454
25     22.871395
26     22.871395
27     22.871395
28     24.068472
29     24.068472
30     24.068472
31     27.394224
32     27.394224
33     27.394224
34           NaN
35           NaN

In [12]:
trimestre = [1,2,3,4,1,2,3,4,1,2,3,4]
ano = [2019,2019,2019,2019,2020,2020,2020,2020,2021,2021,2021,2021]
temperatura = [vect_tri[0],vect_tri[1],vect_tri[4],vect_tri[7],
                 vect_tri[10],vect_tri[13],vect_tri[16],vect_tri[19],
                 vect_tri[22],vect_tri[25],vect_tri[28],vect_tri[31]]
Fin_df = pd.DataFrame()
Fin_df['Temperatura'] = temperatura
Fin_df['Trimestre'] = trimestre
Fin_df['Ano'] = ano
Fin_df['Ciudad'] = ciudad[ci]
Fin_df = Fin_df
Fin_df

    Temperatura  Trimestre   Ano         Ciudad
0     31.214800          1  2019  Villavicencio
1     25.999175          2  2019  Villavicencio
2     26.294418          3  2019  Villavicencio
3     27.479976          4  2019  Villavicencio
4     28.885348          1  2020  Villavicencio
5     25.895681          2  2020  Villavicencio
6     25.798486          3  2020  Villavicencio
7     25.909224          4  2020  Villavicencio
8     28.580454          1  2021  Villavicencio
9     22.871395          2  2021  Villavicencio
10    24.068472          3  2021  Villavicencio
11    27.394224          4  2021  Villavicencio

In [13]:
export_dir = 'TEMP_PRO/'+ ciudad[ci] +'_Pre.csv'
Fin_df.to_csv(export_dir, index=False, header=True)