In [1]:
# Tratamiento de datos
# ==============================================================================
import pandas as pd
import numpy as np


# Configuración warnings
# ==============================================================================
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
dataset_dir = 'Casos_Covid/Casos_positivos_de_COVID-19_en_Colombia.csv' #Se carga el dataset
df_cas = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual está separado por comas
df_cas.isnull().sum() #Se imprime la suma de filas nulas del dataset

C:\Users\sebas\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (14) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

fecha reporte web                     0
ID de caso                            0
Fecha de notificación                 0
Código DIVIPOLA departamento          0
Nombre departamento                   0
Código DIVIPOLA municipio             0
Nombre municipio                      0
Edad                                  0
Unidad de medida de edad              0
Sexo                                  0
Tipo de contagio                      0
Ubicación del caso                34405
Estado                            34405
Código ISO del país             6311064
Nombre del país                 6311056
Recuperado                        29707
Fecha de inicio de síntomas      489332
Fecha de muerte                 6138469
Fecha de diagnóstico               2755
Fecha de recuperación            173861
Tipo de recuperación             173935
Pertenencia étnica                 2112
Nombre del grupo étnico         6231638
dtype: int64

In [3]:
df_cas #Se imprime el dataset

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
0,2021-03-04 00:00:00,2265685,2021-03-02 00:00:00,11,BOGOTA,11001,BOGOTA,49,1,M,...,NaN,NaN,Recuperado,2021-02-25 00:00:00,NaN,2021-03-03 00:00:00,2021-03-16 00:00:00,Tiempo,6.0,NaN
1,2021-03-04 00:00:00,2265686,2021-03-02 00:00:00,11,BOGOTA,11001,BOGOTA,49,1,M,...,NaN,NaN,Recuperado,2021-02-23 00:00:00,NaN,2021-03-03 00:00:00,2021-03-16 00:00:00,Tiempo,6.0,NaN
2,2021-03-04 00:00:00,2265687,2021-03-02 00:00:00,11,BOGOTA,11001,BOGOTA,51,1,F,...,NaN,NaN,Recuperado,2021-02-24 00:00:00,NaN,2021-03-03 00:00:00,2021-03-16 00:00:00,Tiempo,6.0,NaN
3,2021-03-04 00:00:00,2265688,2021-03-02 00:00:00,11,BOGOTA,11001,BOGOTA,51,1,F,...,NaN,NaN,Recuperado,2021-02-27 00:00:00,NaN,2021-03-03 00:00:00,2021-03-13 00:00:00,Tiempo,6.0,NaN
4,2021-03-04 00:00:00,2265689,2021-03-02 00:00:00,11,BOGOTA,11001,BOGOTA,51,1,F,...,NaN,NaN,Recuperado,2021-03-01 00:00:00,NaN,2021-03-03 00:00:00,2021-03-16 00:00:00,Tiempo,6.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6314764,2022-02-05 00:00:00,5956386,2022-01-19 00:00:00,50,META,50001,VILLAVICENCIO,47,1,M,...,NaN,NaN,Recuperado,2022-01-15 00:00:00,NaN,2022-01-30 00:00:00,2022-02-06 00:00:00,Tiempo,6.0,NaN
6314765,2022-02-05 00:00:00,5956387,2022-01-19 00:00:00,50,META,50001,VILLAVICENCIO,39,1,M,...,NaN,NaN,Recuperado,2022-01-15 00:00:00,NaN,2022-01-30 00:00:00,2022-02-06 00:00:00,Tiempo,6.0,NaN
6314766,2022-02-05 00:00:00,5956388,2022-01-19 00:00:00,50,META,50001,VILLAVICENCIO,35,1,M,...,NaN,NaN,Recuperado,2022-01-15 00:00:00,NaN,2022-01-30 00:00:00,2022-02-06 00:00:00,Tiempo,6.0,NaN
6314767,2022-02-05 00:00:00,5956389,2022-01-19 00:00:00,50,META,50001,VILLAVICENCIO,11,1,M,...,NaN,NaN,Recuperado,2022-01-15 00:00:00,NaN,2022-01-30 00:00:00,2022-02-06 00:00:00,Tiempo,6.0,NaN
6314768,2022-02-05 00:00:00,5956390,2022-01-19 00:00:00,50,META,50001,VILLAVICENCIO,34,1,F,...,NaN,NaN,Recuperado,2022-01-15 00:00:00,NaN,2022-01-30 00:00:00,2022-02-06 00:00:00,Tiempo,6.0,NaN

In [4]:
df_cas_d = df_cas.drop(['fecha reporte web','Edad','Unidad de medida de edad',
           'Nombre del grupo étnico','Pertenencia étnica','Tipo de recuperación',
          'Fecha de recuperación','Ubicación del caso','Código ISO del país',
             'Tipo de contagio','Recuperado','Fecha de inicio de síntomas'
            ,'Estado','Sexo','Fecha de muerte','Nombre del país','Fecha de notificación',
            'ID de caso'], axis=1) #Se eliminan las columnas que no aportan información importante para este trabajo
df_cas_d #Se imprime el dataset

,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Fecha de diagnóstico
0,11,BOGOTA,11001,BOGOTA,2021-03-03 00:00:00
1,11,BOGOTA,11001,BOGOTA,2021-03-03 00:00:00
2,11,BOGOTA,11001,BOGOTA,2021-03-03 00:00:00
3,11,BOGOTA,11001,BOGOTA,2021-03-03 00:00:00
4,11,BOGOTA,11001,BOGOTA,2021-03-03 00:00:00
...,...,...,...,...,...
6314764,50,META,50001,VILLAVICENCIO,2022-01-30 00:00:00
6314765,50,META,50001,VILLAVICENCIO,2022-01-30 00:00:00
6314766,50,META,50001,VILLAVICENCIO,2022-01-30 00:00:00
6314767,50,META,50001,VILLAVICENCIO,2022-01-30 00:00:00
6314768,50,META,50001,VILLAVICENCIO,2022-01-30 00:00:00

In [5]:
date = df_cas_d["Fecha de diagnóstico"].str.split('-', expand=True) #Se divide la columna "Fecha de diagnóstico"
date.columns = ['Ano','Mes','Dia'] # en año, mes y día 
df_cas_n = pd.concat([df_cas_d, date], axis=1) # Se agregan las columnas creadas al dataset
df_cas_n = df_cas_n.drop(['Fecha de diagnóstico','Dia'], axis=1) # Se borran las siguientes columnas
df_cas_n #Se imprime el dataset

,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Ano,Mes
0,11,BOGOTA,11001,BOGOTA,2021,03
1,11,BOGOTA,11001,BOGOTA,2021,03
2,11,BOGOTA,11001,BOGOTA,2021,03
3,11,BOGOTA,11001,BOGOTA,2021,03
4,11,BOGOTA,11001,BOGOTA,2021,03
...,...,...,...,...,...,...
6314764,50,META,50001,VILLAVICENCIO,2022,01
6314765,50,META,50001,VILLAVICENCIO,2022,01
6314766,50,META,50001,VILLAVICENCIO,2022,01
6314767,50,META,50001,VILLAVICENCIO,2022,01
6314768,50,META,50001,VILLAVICENCIO,2022,01

In [6]:
#Para crear la base del nuevo dataset
df_cas_n = df_cas_n.drop(df_cas_n[df_cas_n['Ano'] == ('2022' or '2019')].index) #Se eliminan las filas cuyo columna indicada sea igual a 2019 o 2022
df_cas_n.reset_index(drop=True, inplace=True) #Se reinicia el index, con el fin de que el número de cada fila quede ordenado

In [7]:
df_cas_n['Código DIVIPOLA departamento'].unique().tolist() #se listan los diferente datos de esta columna
#Se observa que hay datos que se deben corregir

[11,
 52,
 68,
 66,
 15,
 54,
 5,
 18,
 50,
 76,
 20,
 8001,
 41,
 99,
 86,
 19,
 47,
 23,
 8,
 25,
 17,
 70,
 47001,
 73,
 13001,
 63,
 44,
 13,
 91,
 85,
 81,
 27,
 95,
 88,
 97,
 94]

In [8]:
#Al imprimir una ciudad se observa que el nombre esta en mayúsculas, por lo que se debe arreglar al estandár
df_cas_t = df_cas_n[df_cas_n["Nombre municipio"] == "VILLAVICENCIO"]
df_cas_t

,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Ano,Mes
49,50,META,50001,VILLAVICENCIO,2020,09
83,50,META,50001,VILLAVICENCIO,2020,09
132,50,META,50001,VILLAVICENCIO,2021,03
136,50,META,50001,VILLAVICENCIO,2021,03
140,50,META,50001,VILLAVICENCIO,2021,03
...,...,...,...,...,...,...
5194465,50,META,50001,VILLAVICENCIO,2021,12
5194471,50,META,50001,VILLAVICENCIO,2021,12
5194479,50,META,50001,VILLAVICENCIO,2021,12
5195903,50,META,50001,VILLAVICENCIO,2021,09
5196173,50,META,50001,VILLAVICENCIO,2021,11

In [9]:
#Se reasigna el nombre de la ciudad para que quede estándar con los demás datasets
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "ARMENIA"] = "Armenia" 
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "BARRANQUILLA"] = "Barranquilla" 
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "BOGOTA"] = "Bogota" 
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "BUCARAMANGA"] = "Bucaramanga"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "CALI"] = "Cali"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "CARTAGENA"] = "Cartagena"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "CUCUTA"] = "Cucuta"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "FLORENCIA"] = "Florencia"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "IBAGUE"] = "Ibague"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "MANIZALES"] = "Manizales"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "MEDELLIN"] = "Medellin"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "MONTERIA"] = "Monteria"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "NEIVA"] = "Neiva"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "PASTO"] = "Pasto"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "PEREIRA"] = "Pereira"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "POPAYAN"] = "Popayan"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "QUIBDO"] = "Quibdo"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "RIOHACHA"] = "Riohacha"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "SAN ANDRES"] = "Sanandres"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "SANTA MARTA"] = "Santamarta"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "SINCELEJO"] = "Sincelejo"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "TUNJA"] = "Tunja"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "VALLEDUPAR"] = "Valledupar"
df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "VILLAVICENCIO"] = "Villavicencio"

<ipython-input-9-f3f068e375b7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "ARMENIA"] = "Armenia"
<ipython-input-9-f3f068e375b7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "BARRANQUILLA"] = "Barranquilla"
<ipython-input-9-f3f068e375b7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "BOGOTA"] = "Bogota"
<ipython-input-9-f3f068e375b7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "BUCARAMANGA"] = "Bucaramanga"
<ipython-input-9-f3f068e375b7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "CALI"] = "Cali"
<ipython-input-9-f3f068e375b7>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "CARTAGENA"] = "Cartagena"
<ipython-input-9-f3f068e375b7>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "CUCUTA"] = "Cucuta"
<ipython-input-9-f3f068e375b7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "FLORENCIA"] = "Florencia"
<ipython-input-9-f3f068e375b7>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "IBAGUE"] = "Ibague"
<ipython-input-9-f3f068e375b7>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "MANIZALES"] = "Manizales"
<ipython-input-9-f3f068e375b7>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "MEDELLIN"] = "Medellin"
<ipython-input-9-f3f068e375b7>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "MONTERIA"] = "Monteria"
<ipython-input-9-f3f068e375b7>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "NEIVA"] = "Neiva"
<ipython-input-9-f3f068e375b7>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "PASTO"] = "Pasto"
<ipython-input-9-f3f068e375b7>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "PEREIRA"] = "Pereira"
<ipython-input-9-f3f068e375b7>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "POPAYAN"] = "Popayan"
<ipython-input-9-f3f068e375b7>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "QUIBDO"] = "Quibdo"
<ipython-input-9-f3f068e375b7>:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "RIOHACHA"] = "Riohacha"
<ipython-input-9-f3f068e375b7>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "SAN ANDRES"] = "Sanandres"
<ipython-input-9-f3f068e375b7>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "SANTA MARTA"] = "Santamarta"
<ipython-input-9-f3f068e375b7>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "SINCELEJO"] = "Sincelejo"
<ipython-input-9-f3f068e375b7>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "TUNJA"] = "Tunja"
<ipython-input-9-f3f068e375b7>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "VALLEDUPAR"] = "Valledupar"
<ipython-input-9-f3f068e375b7>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cas_n["Nombre municipio"][df_cas_n["Nombre municipio"] == "VILLAVICENCIO"] = "Villavicencio"

In [ ]:
#Se corrigen los datos que se observaron mal anteriormente
df_cas_n["Código DIVIPOLA departamento"][df_cas_n["Código DIVIPOLA departamento"] == 8001] = 8
df_cas_n["Código DIVIPOLA departamento"][df_cas_n["Código DIVIPOLA departamento"] == 47001] = 47
df_cas_n["Código DIVIPOLA departamento"][df_cas_n["Código DIVIPOLA departamento"] == 13001] = 13
df_cas_n['Código DIVIPOLA departamento'].unique().tolist() # Se lista nuevamente para comprobar la correción

In [ ]:
#Se crea un vector con los nombres de las ciudades
ciudad = ['Armenia','Barranquilla','Bogota','Bucaramanga',
       'Cali','Cartagena','Cucuta','Florencia','Ibague',
       'Manizales','Medellin','Monteria','Neiva','Pasto',
       'Pereira','Popayan','Quibdo','Riohacha','Sanandres',
       'Santamarta','Sincelejo','Tunja','Valledupar',
          'Villavicencio']
#Se crea un vector con los códigos de los departamentos
cod = [63,8,11,68,
      76,13,54,18,73,
      17,5,23,41,52,
      66,19,27,44,88,
       47,70,15,20,50]

#La variable "ci" se reemplaza por números del 0 al 23 y 
# se corre nuevamente a partir de esta sección, al final
# se obtiene un archivo CSV para cada ciudad
ci = 23 #Se crea un vector con la cantidad de ciudades

In [ ]:
df_casos = df_cas_n[df_cas_n['Nombre municipio'] == ciudad[ci]].fillna(0) #Se asigna un cero a los valores nulos
df_casos = df_casos[df_casos['Código DIVIPOLA departamento'] == cod[ci]] #Se filtra por el código del departamento
df_casos = df_casos.sort_values(['Ano','Mes']) #Se organizan segun el año y el mes

In [ ]:
df_casos['Ano'].unique().tolist() #Se lista los diferentes datos para la columna "Ano"

In [ ]:
#Se crea un dataset base conrespondiente cada fila a un mes
mes = [1,2,3,4,5,6,7,8,9,10,11,12,1,2,3,4,5,6,7,8,9,10,11,12] #Se crea un vector con el número del mes
ano = [2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,2020,
      2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021] #Se crea un vector con el número del año
dataset_v = pd.DataFrame() #Se establece la variable como DataFrame
#En cada columna de este dataset se le asigna su correspondiente vector
dataset_v['Mes'] = mes
dataset_v['Ano'] = ano
dataset_v['Ciudad'] = ciudad[ci] #El resultado obtiene el contenido de cada ciudad


dataset_v #Se imprime el dataset

In [ ]:
df_casos.info() #Se imprime la información del dataset
df_casos['Mes'] = df_casos['Mes'].astype('int64') #Se corrige el tipo de datos de las variables
df_casos['Ano'] = df_casos['Ano'].astype('int64')
df_casos #Se imprime el dataset

In [ ]:
val_mes = dataset_v['Mes'] #Se guardan los valores de la columna 
val_ano = dataset_v['Ano'] #Se guardan los valores de la columna 

vect_a = [] #Se crea un vector vacío

#Se crea un ciclo for para obtener la suma de los datos agrupandolos mensualmente
for n_Mes,n_Ano in zip(val_mes,val_ano):
    vect_a.append(df_casos.apply(lambda x: ((x['Ano'] == n_Ano) and (x['Mes'] == n_Mes )), axis=1).sum())

print(vect_a) #Se imprime el valor obtenido para cada mes
dataset_v['Casos Covid'] = vect_a # Se asigna el resultado a la columna del dataset
dataset_v #Se imprime el resultado

In [ ]:
#Se realiza la agrupación trimestral de los datos
vect_tri_a = [] #Se crea un vector vacío para la variable

df_agr = pd.DataFrame() #Se establece la variable como DataFrame
df_agr['Casos Covid'] = None #Se crea la columna vacia para el nuevo dataset

c = [0,3,6,9,12,15,18,21,24,27,30,33,36,39] #Se crea un vector para el resultado trimestral
i = 0#Se inicializa el contador

#Se crea un ciclo for para obtener un promedio de los datos agrupandolos trimestralmente
for n in dataset_v['Mes'].index:
    vect_tri_a.append(dataset_v.loc[(dataset_v['Mes'].index >= c[i]) & (dataset_v['Mes'].index < c[i+1]),'Casos Covid'].sum())
    
    if n == c[i]: #Incremento del contador
        i = 1+i
# Se asigna el resultado a cada columna del nuevo dataset       
df_agr['Casos Covid'] = vect_tri_a

df_agr #Se imprime el dataset

In [ ]:
#Se crea el dataset con información trimestral
trimestre = [1,2,3,4,1,2,3,4,1,2,3,4] # Se crea un vector para el nuevo valor por trimestre
ano = [2019,2019,2019,2019,2020,2020,2020,2020,2021,2021,2021,2021] #Se crea un vector para el nuevo vector de trimestre segun el año
#Se crea un vector con la información resultante de cada trimestre
casos_covid = [0,0,0,0,vect_tri_a[0],vect_tri_a[1],vect_tri_a[4],vect_tri_a[7],
                 vect_tri_a[10],vect_tri_a[13],vect_tri_a[16],vect_tri_a[19]]

df_casos_covid = pd.DataFrame() #Se establece la variable como DataFrame
df_casos_covid['Trimestre'] = trimestre
df_casos_covid['Ano'] = ano
df_casos_covid['Ciudad'] = ciudad[ci] #El resultado obtiene el contenido de cada ciudad
df_casos_covid['Casos Covid'] = casos_covid

df_casos_covid #Se imprime el dataset

In [ ]:
export_dir = 'Casos_Covid/C_'+ ciudad[ci] +'_Pre.csv' #Se establece la dirección y nombre para exportar el dataset resultante
df_casos_covid.to_csv(export_dir, index=False, header=True) #Se exporta el dataset en formato CSV