## Se unen los dataframes

In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
# Configuraci√≥n warnings
# ==============================================================================
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [2]:
dataset_dir = 'TG2022_Datos\Departamentos_CSV\Pre_Departamentos_personas_procesado_10.csv' #Se carga el dataset
df_dataset = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual est√° separado por comas

df_dataset

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,19,1,Cauca,133282,143988,17049,18044,19187,22270,25292,...,23666,37041,12882,6503,4941,17049,4267,114740,118992,39271
1,19,22,Cauca,8279,8244,1075,1227,1421,1562,1456,...,215,225,60,1493,86,1075,145,4497,9579,2302
2,19,50,Cauca,10513,9623,1475,1811,1869,2021,1924,...,213,267,77,1368,340,1475,214,7867,8558,3497
3,19,75,Cauca,9513,9397,1341,1420,1796,1767,1711,...,406,274,90,1258,140,1341,272,6933,8940,2765
4,19,100,Cauca,18234,17603,2152,2535,2848,3116,3034,...,645,695,240,2369,188,2152,318,12609,18015,4895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,76,863,Valle del Cauca,3082,3151,346,433,428,513,440,...,234,119,61,441,44,346,95,2367,2992,779
209,76,869,Valle del Cauca,5437,5329,582,718,798,820,822,...,777,376,71,410,114,582,158,4608,4675,1325
210,76,890,Valle del Cauca,7665,7660,859,975,1222,1255,1192,...,1055,612,78,703,71,859,107,6699,6679,1840
211,76,892,Valle del Cauca,46002,49038,5674,6162,7139,7942,8488,...,7733,5458,946,2773,958,5674,1153,43407,38472,12008
212,76,895,Valle del Cauca,18660,20683,2343,2562,2987,3432,3389,...,3091,2572,469,1533,378,2343,445,16735,17215,4948

In [3]:
#El prop√≥sito de las siguientes l√≠neas, es revisar cu√°ntos municipios hay.
df_agrup_pers = df_dataset.drop_duplicates(subset=['U_DPTO','U_MPIO'],keep='last', inplace=False) #Se borran todas las filas
#En las cuales los municipios est√°n duplicados
df_agrup_pers.reset_index(drop=True, inplace=True)#Se reinicia el index, con el fin de que el n√∫mero de cada fila quede ordenado

df_agrup_pers#Se imprime el dataset

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,19,1,Cauca,133282,143988,17049,18044,19187,22270,25292,...,23666,37041,12882,6503,4941,17049,4267,114740,118992,39271
1,19,22,Cauca,8279,8244,1075,1227,1421,1562,1456,...,215,225,60,1493,86,1075,145,4497,9579,2302
2,19,50,Cauca,10513,9623,1475,1811,1869,2021,1924,...,213,267,77,1368,340,1475,214,7867,8558,3497
3,19,75,Cauca,9513,9397,1341,1420,1796,1767,1711,...,406,274,90,1258,140,1341,272,6933,8940,2765
4,19,100,Cauca,18234,17603,2152,2535,2848,3116,3034,...,645,695,240,2369,188,2152,318,12609,18015,4895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,76,863,Valle del Cauca,3082,3151,346,433,428,513,440,...,234,119,61,441,44,346,95,2367,2992,779
209,76,869,Valle del Cauca,5437,5329,582,718,798,820,822,...,777,376,71,410,114,582,158,4608,4675,1325
210,76,890,Valle del Cauca,7665,7660,859,975,1222,1255,1192,...,1055,612,78,703,71,859,107,6699,6679,1840
211,76,892,Valle del Cauca,46002,49038,5674,6162,7139,7942,8488,...,7733,5458,946,2773,958,5674,1153,43407,38472,12008
212,76,895,Valle del Cauca,18660,20683,2343,2562,2987,3432,3389,...,3091,2572,469,1533,378,2343,445,16735,17215,4948

In [4]:
val_pers_mun = df_agrup_pers['U_MPIO'] #Se guardan los valores de la columna U_MPIO
val_pers_dpto = df_agrup_pers['U_DPTO'] #Se guardan los valores de la columna U_DPTO

vect_a = [] #Se crea un vector vac√≠o
vect_0 = [] #Se crea un vector vac√≠o
vect_1 = [] #Se crea un vector vac√≠o
vect_2 = [] #Se crea un vector vac√≠o
vect_3 = [] #Se crea un vector vac√≠o
vect_4 = [] #Se crea un vector vac√≠o
vect_5 = [] #Se crea un vector vac√≠o
vect_6 = [] #Se crea un vector vac√≠o
vect_7 = [] #Se crea un vector vac√≠o
vect_8 = [] #Se crea un vector vac√≠o
vect_9 = [] #Se crea un vector vac√≠o
vect_10 = [] #Se crea un vector vac√≠o
vect_11 = [] #Se crea un vector vac√≠o
vect_12 = [] #Se crea un vector vac√≠o
vect_13 = [] #Se crea un vector vac√≠o
vect_14 = [] #Se crea un vector vac√≠o
vect_15 = [] #Se crea un vector vac√≠o
vect_16 = [] #Se crea un vector vac√≠o
vect_17 = [] #Se crea un vector vac√≠o
vect_18 = [] #Se crea un vector vac√≠o
vect_19 = [] #Se crea un vector vac√≠o
vect_20 = [] #Se crea un vector vac√≠o
vect_21 = [] #Se crea un vector vac√≠o
vect_22 = [] #Se crea un vector vac√≠o
vect_23 = [] #Se crea un vector vac√≠o
vect_24 = [] #Se crea un vector vac√≠o
vect_25 = [] #Se crea un vector vac√≠o
vect_26 = [] #Se crea un vector vac√≠o
vect_27 = [] #Se crea un vector vac√≠o
vect_28 = [] #Se crea un vector vac√≠o
vect_29 = [] #Se crea un vector vac√≠o
vect_30 = [] #Se crea un vector vac√≠o
vect_31 = [] #Se crea un vector vac√≠o
vect_32 = [] #Se crea un vector vac√≠o
#vect_33 = [] #Se crea un vector vac√≠o
vect_34 = [] #Se crea un vector vac√≠o
vect_35 = [] #Se crea un vector vac√≠o
vect_36 = [] #Se crea un vector vac√≠o
vect_37 = [] #Se crea un vector vac√≠o
vect_38 = [] #Se crea un vector vac√≠o
vect_39 = [] #Se crea un vector vac√≠o
vect_40 = [] #Se crea un vector vac√≠o
vect_41 = [] #Se crea un vector vac√≠o
vect_42 = [] #Se crea un vector vac√≠o
vect_43 = [] #Se crea un vector vac√≠o
vect_44 = [] #Se crea un vector vac√≠o
vect_45 = [] #Se crea un vector vac√≠o
vect_46 = [] #Se crea un vector vac√≠o
vect_47 = [] #Se crea un vector vac√≠o
vect_48 = [] #Se crea un vector vac√≠o
vect_49 = [] #Se crea un vector vac√≠o
vect_50 = [] #Se crea un vector vac√≠o
vect_51 = [] #Se crea un vector vac√≠o
vect_52 = [] #Se crea un vector vac√≠o
vect_53 = [] #Se crea un vector vac√≠o
vect_54 = [] #Se crea un vector vac√≠o



for n_MPIO,n_DPTO in zip(val_pers_mun,val_pers_dpto): #El ZIP se usa para empezar a asociar cada departamento con el respectivo municipio
    #Se realiza la comparacion entre el n√∫mero de municipio y el de departamento, en el caso de que sean iguales
    #Se van sumando y se van guardando en un vector seg√∫n el tipo de vivienda
    vect_a.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_Hombre'].sum())
    vect_0.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_Mujer'].sum())
    vect_1.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_0 a 4'].sum())
    vect_2.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_5 a 9'].sum())
    vect_3.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_10 a 14'].sum())
    vect_4.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_15 a 19'].sum())
    vect_5.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_20 a 24'].sum())
    vect_6.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_25 a 29'].sum())
    vect_7.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_30 a 34'].sum())
    vect_8.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_35 a 39'].sum())
    vect_9.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_40 a 44'].sum())
    vect_10.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_45 a 49'].sum())
    vect_11.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_50 a 54'].sum())
    vect_12.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_55 a 59'].sum())
    vect_13.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Per_edad_Mas de 60'].sum())
    vect_14.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Indigena'].sum())
    vect_15.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Gitano o Rrom'].sum())
    vect_16.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Raizal del Archi SAPSC'].sum())
    vect_17.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Palenquero de San Basilio'].sum())
    vect_18.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Negro, mulato, afrodescendiente, afrocolombiano'].sum())
    vect_19.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Ningun grupo etnico'].sum())
    vect_20.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No informa grupo etnico'].sum())
    vect_21.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Habla lengua Nativa'].sum())
    vect_22.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No habla lengua nativa'].sum())
    vect_23.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No informa lengua nativa'].sum())
    vect_24.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No aplica lengua nativa'].sum())
    vect_25.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Habla otra lengua'].sum())
    vect_26.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No habla otra lengua'].sum())
    vect_27.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No informa otra lengua'].sum())
    vect_28.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No aplica otra lengua'].sum())
    vect_29.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'CSS muy bueno'].sum())
    vect_30.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'CSS bueno'].sum())
    vect_31.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'CSS malo'].sum())
    vect_32.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'CSS muy malo'].sum())
#    vect_33.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No informa Calidad de servicio'].sum())
    vect_34.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'CSS No Aplica'].sum())
    vect_35.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Lee_y_Escribe'].sum())
    vect_36.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'NoLee_y_Escribe'].sum())
    vect_37.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No_informa_Alfabeta'].sum())
    vect_38.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No Aplica P_ALFABETA'].sum())
    vect_39.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Preescolar'].sum())
    vect_40.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Primaria'].sum())
    vect_41.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Secundaria'].sum())
    vect_42.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Media_Academica'].sum())
    vect_43.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Media_tecnica'].sum())
    vect_44.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Normalista'].sum())
    vect_45.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Tecnica_Profesional'].sum())
    vect_46.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Universitario'].sum())
    vect_47.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Posgrado'].sum())
    vect_48.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Ninguno'].sum())
    vect_49.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No_inf_escolaridad'].sum())
    vect_50.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No Aplica P_NIVEL_ANOSR'].sum())
    vect_51.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No informa ingresos'].sum())
    vect_52.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'Recibe ingresos'].sum())
    vect_53.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No recibe ingresos'].sum())
    vect_54.append(df_dataset.loc[(df_dataset['U_MPIO'] == n_MPIO) & (df_dataset['U_DPTO'] == n_DPTO) ,'No Aplica ingresos'].sum())

df_agrup_pers['Per_Hombre'] = vect_a
df_agrup_pers['Per_Mujer'] = vect_0
df_agrup_pers['Per_0 a 4'] = vect_1 #En el nuevo dataframe, a cada columna se le asigna el total de cada tipo de vivienda
df_agrup_pers['Per_5 a 9'] = vect_2
df_agrup_pers['Per_10 a 14'] = vect_3
df_agrup_pers['Per_15 a 19'] = vect_4
df_agrup_pers['Per_20 a 24'] = vect_5
df_agrup_pers['Per_25 a 29'] = vect_6
df_agrup_pers['Per_30 a 34'] = vect_7
df_agrup_pers['Per_35 a 39'] = vect_8
df_agrup_pers['Per_40 a 44'] = vect_9
df_agrup_pers['Per_45 a 49'] = vect_10 #En el nuevo dataframe, a cada columna se le asigna el total de cada tipo de vivienda
df_agrup_pers['Per_50 a 54'] = vect_11
df_agrup_pers['Per_55 a 59'] = vect_12
df_agrup_pers['Per_Mas de 60'] = vect_13
df_agrup_pers['Indigena'] = vect_14
df_agrup_pers['Gitano o Rrom'] = vect_15
df_agrup_pers['Raizal del Archi SAPSC'] = vect_16
df_agrup_pers['Palenquero de San Basilio'] = vect_17
df_agrup_pers['Negro, mulato, afrodescendiente, afrocolombiano'] = vect_18
df_agrup_pers['Ningun grupo etnico'] = vect_19 #En el nuevo dataframe, a cada columna se le asigna el total de cada tipo de vivienda
df_agrup_pers['No informa grupo etnico'] = vect_20
df_agrup_pers['Habla lengua Nativa'] = vect_21
df_agrup_pers['No habla lengua nativa'] = vect_22
df_agrup_pers['No informa lengua nativa'] = vect_23
df_agrup_pers['No aplica lengua nativa'] = vect_24
df_agrup_pers['Habla otra lengua'] = vect_25
df_agrup_pers['No habla otra lengua'] = vect_26
df_agrup_pers['No informa otra lengua'] = vect_27
df_agrup_pers['No aplica otra lengua'] = vect_28 #En el nuevo dataframe, a cada columna se le asigna el total de cada tipo de vivienda
df_agrup_pers['CSS muy bueno'] = vect_29
df_agrup_pers['CSS bueno'] = vect_30
df_agrup_pers['CSS malo'] = vect_31
df_agrup_pers['CSS muy malo'] = vect_32
#df_agrup_pers['No informa Calidad de servicio'] = vect_33
df_agrup_pers['CSS No Aplica'] = vect_34
df_agrup_pers['Lee_y_Escribe'] = vect_35 #En el nuevo dataframe, a cada columna se le asigna el total de cada tipo de vivienda
df_agrup_pers['NoLee_y_Escribe'] = vect_36
df_agrup_pers['No_informa_Alfabeta'] = vect_37
df_agrup_pers['No Aplica P_ALFABETA'] = vect_38
df_agrup_pers['Preescolar'] = vect_39
df_agrup_pers['Primaria'] = vect_40
df_agrup_pers['Secundaria'] = vect_41
df_agrup_pers['Media_Academica'] = vect_42
df_agrup_pers['Media_tecnica'] = vect_43
df_agrup_pers['Normalista'] = vect_44
df_agrup_pers['Tecnica_Profesional'] = vect_45 #En el nuevo dataframe, a cada columna se le asigna el total de cada tipo de vivienda
df_agrup_pers['Universitario'] = vect_46
df_agrup_pers['Posgrado'] = vect_47
df_agrup_pers['Ninguno'] = vect_48
df_agrup_pers['No_inf_escolaridad'] = vect_49
df_agrup_pers['No Aplica P_NIVEL_ANOSR'] = vect_50
df_agrup_pers['No informa ingresos'] = vect_51
df_agrup_pers['Recibe ingresos'] = vect_52
df_agrup_pers['No recibe ingresos'] = vect_53
df_agrup_pers['No Aplica ingresos'] = vect_54 #En el nuevo dataframe, a cada columna se le asigna el total de cada tipo de vivienda



df_agrup_pers

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Per_15 a 19,Per_20 a 24,Per_25 a 29,Per_30 a 34,Per_35 a 39,Per_40 a 44,Per_45 a 49,Per_50 a 54,Per_55 a 59,Per_Mas de 60
0,19,1,Cauca,133282,143988,17049,18044,19187,22270,25292,...,22270,25292,23812,22775,22293,17979,16995,16946,14836,39792
1,19,22,Cauca,8279,8244,1075,1227,1421,1562,1456,...,1562,1456,1229,1305,1301,946,838,792,795,2576
2,19,50,Cauca,10513,9623,1475,1811,1869,2021,1924,...,2021,1924,1891,1831,1641,1213,1020,918,791,1731
3,19,75,Cauca,9513,9397,1341,1420,1796,1767,1711,...,1767,1711,1464,1425,1385,1201,1042,959,894,2505
4,19,100,Cauca,18234,17603,2152,2535,2848,3116,3034,...,3116,3034,2711,2661,2784,2231,2098,1944,1846,5877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,76,863,Valle del Cauca,3082,3151,346,433,428,513,440,...,513,440,425,367,416,326,450,441,420,1228
209,76,869,Valle del Cauca,5437,5329,582,718,798,820,822,...,820,822,807,733,757,721,691,691,627,1999
210,76,890,Valle del Cauca,7665,7660,859,975,1222,1255,1192,...,1255,1192,1167,1059,1058,925,1088,1065,877,2583
211,76,892,Valle del Cauca,46002,49038,5674,6162,7139,7942,8488,...,7942,8488,8162,7367,7255,6231,6310,6138,5211,12961
212,76,895,Valle del Cauca,18660,20683,2343,2562,2987,3432,3389,...,3432,3389,2932,2691,2791,2517,2580,2555,2202,6362

In [5]:
#export_dir = 'TG2022_Datos/Departamentos_CSV/Pre_Departamentos_personas_procesado_10.csv'
#df_agrup_pers_final.to_csv(export_dir, index=False, header=True)

In [6]:
dataset_dir = 'TG2022_Datos\Departamentos_CSV\Pre_Departamentos_personas_procesado_10.csv' #Se carga el dataset
df_d_1 = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual est√° separado por comas
df_d_1

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,19,1,Cauca,133282,143988,17049,18044,19187,22270,25292,...,23666,37041,12882,6503,4941,17049,4267,114740,118992,39271
1,19,22,Cauca,8279,8244,1075,1227,1421,1562,1456,...,215,225,60,1493,86,1075,145,4497,9579,2302
2,19,50,Cauca,10513,9623,1475,1811,1869,2021,1924,...,213,267,77,1368,340,1475,214,7867,8558,3497
3,19,75,Cauca,9513,9397,1341,1420,1796,1767,1711,...,406,274,90,1258,140,1341,272,6933,8940,2765
4,19,100,Cauca,18234,17603,2152,2535,2848,3116,3034,...,645,695,240,2369,188,2152,318,12609,18015,4895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,76,863,Valle del Cauca,3082,3151,346,433,428,513,440,...,234,119,61,441,44,346,95,2367,2992,779
209,76,869,Valle del Cauca,5437,5329,582,718,798,820,822,...,777,376,71,410,114,582,158,4608,4675,1325
210,76,890,Valle del Cauca,7665,7660,859,975,1222,1255,1192,...,1055,612,78,703,71,859,107,6699,6679,1840
211,76,892,Valle del Cauca,46002,49038,5674,6162,7139,7942,8488,...,7733,5458,946,2773,958,5674,1153,43407,38472,12008
212,76,895,Valle del Cauca,18660,20683,2343,2562,2987,3432,3389,...,3091,2572,469,1533,378,2343,445,16735,17215,4948

In [7]:
dataset_dir = 'TG2022_Datos\Departamentos_CSV\Pre_Departamentos_personas_procesado_11.csv' #Se carga el dataset
df_d_2 = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual est√° separado por comas
df_d_2

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,15,1,Boyaca,79244,88747,10769,11965,13333,15263,16732,...,14096,29556,14337,3156,4044,10769,3056,74049,67046,23840
1,15,22,Boyaca,830,752,67,87,104,127,71,...,35,48,18,88,16,67,24,493,911,154
2,15,47,Boyaca,7045,6815,1006,1209,1312,1287,1012,...,289,380,77,837,106,1006,202,5435,6008,2215
3,15,51,Boyaca,2729,2736,386,424,495,531,414,...,200,261,66,178,28,386,45,2650,1942,828
4,15,87,Boyaca,3502,3820,459,545,620,682,534,...,367,414,103,289,59,459,90,2565,3663,1004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,44,560,La Guajira,36421,38107,11783,11083,9611,8485,6621,...,769,1569,140,15064,641,11783,943,13602,35945,24038
212,44,650,La Guajira,22765,23312,4095,4351,4446,4406,4027,...,4240,3301,567,2693,408,4095,712,14655,21996,8714
213,44,847,La Guajira,77668,83043,20012,21619,19185,18187,15525,...,1568,2429,352,38673,1797,20012,2255,22657,91748,44051
214,44,855,La Guajira,5048,5150,867,874,911,1010,846,...,933,1051,104,530,119,867,269,2929,5248,1752
215,44,874,La Guajira,12234,12762,2235,2357,2520,2281,2103,...,2020,2558,222,1321,179,2235,473,7636,12266,4621

In [8]:
dataset_dir = 'TG2022_Datos\Departamentos_CSV\Pre_Departamentos_personas_procesado_12.csv' #Se carga el dataset
df_d_3 = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual est√° separado por comas
df_d_3

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,5,1,Antioquia,1115273,1257057,122409,130298,153496,184184,226773,...,245278,280569,82299,54515,35524,122409,38570,1155530,914201,264029
1,5,2,Antioquia,9139,8460,923,1135,1490,1606,1232,...,433,304,149,1230,143,923,235,7220,8060,2084
2,5,4,Antioquia,1171,988,131,135,169,212,176,...,107,58,23,99,27,131,32,819,1024,284
3,5,21,Antioquia,1912,1927,253,283,321,322,263,...,214,112,28,166,43,253,66,1456,1768,549
4,5,30,Antioquia,13242,13579,1455,1587,1996,2290,2321,...,1600,792,189,1400,128,1455,235,11472,11939,3175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,70,717,Sucre,9124,8905,1369,1716,1694,1578,1389,...,769,650,138,1743,92,1369,307,5133,9485,3104
247,70,742,Sucre,15249,14939,2357,2510,2686,2615,2460,...,986,1324,325,2767,153,2357,452,9082,15787,4867
248,70,771,Sucre,12944,11027,1964,2357,2352,2070,1707,...,612,674,111,3099,124,1964,275,6503,12872,4321
249,70,820,Sucre,15813,16199,2975,3010,3135,3244,2666,...,2098,1392,257,2062,170,2975,323,11017,14687,5985
250,70,823,Sucre,10216,9817,1585,1763,2018,1860,1620,...,926,796,93,1960,119,1585,274,6895,9516,3348

In [9]:
dataset_dir = 'TG2022_Datos\Departamentos_CSV\Pre_Departamentos_personas_procesado_13.csv' #Se carga el dataset
df_d_4 = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual est√° separado por comas
df_d_4

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,8,1,Atlantico,536790,583313,79260,82171,84712,94976,98201,...,109295,166943,32967,22655,15819,79260,17861,478042,458276,165924
1,8,78,Atlantico,30695,30832,4702,4981,5295,5508,5067,...,4521,3610,502,2124,601,4702,839,21340,29599,9749
2,8,137,Atlantico,11394,11416,2049,2183,2219,2130,1872,...,627,632,58,2081,162,2049,455,4347,13776,4232
3,8,141,Atlantico,7961,7670,1382,1612,1475,1500,1312,...,607,329,33,1857,166,1382,308,4264,8065,2994
4,8,296,Atlantico,27613,27510,4864,4883,4953,5234,4855,...,3855,3349,268,1814,403,4864,748,18097,26424,9854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,68,855,Santander,2861,2787,390,417,462,492,468,...,209,288,82,350,51,390,125,2219,2497,807
248,68,861,Santander,10161,9215,1023,1120,1464,2087,1789,...,1466,955,387,1363,270,1023,272,7166,8821,3117
249,68,867,Santander,900,862,103,121,142,145,144,...,134,50,7,47,16,103,8,551,979,224
250,68,872,Santander,3282,3456,414,490,537,552,458,...,309,346,106,219,83,414,81,2768,2972,917
251,68,895,Santander,4377,4620,574,756,773,734,513,...,323,357,145,317,69,574,77,3770,3688,1462

In [10]:
dataset_dir = 'TG2022_Datos\Departamentos_CSV\Pre_Departamentos_personas_procesado_14.csv' #Se carga el dataset
df_d_5 = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual est√° separado por comas
df_d_5

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,91,1,Amazonas,22047,20797,4393,4571,5000,5067,3862,...,2605,1784,659,1162,1511,4393,893,14677,16871,10403
1,91,263,Amazonas,1029,856,198,275,278,292,142,...,36,25,0,38,193,198,138,333,748,666
2,91,405,Amazonas,1316,1041,252,405,434,383,141,...,31,28,10,35,96,252,77,126,1054,1100
3,91,407,Amazonas,1985,1796,438,456,568,572,336,...,15,26,5,180,245,438,178,322,2116,1165
4,91,430,Amazonas,85,81,18,23,22,29,11,...,2,0,0,24,16,18,5,3,117,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,94,884,Guainia,862,781,129,327,263,228,111,...,0,4,1,96,135,129,110,78,748,707
159,94,885,Guainia,118,104,21,48,43,21,17,...,0,4,0,13,12,21,11,35,72,104
160,94,886,Guainia,429,410,71,187,162,99,50,...,3,2,1,83,12,71,9,151,293,386
161,94,887,Guainia,630,552,133,185,212,146,111,...,0,1,1,99,87,133,53,17,627,485
162,94,888,Guainia,422,390,86,136,141,112,71,...,2,5,0,94,15,86,13,30,436,333

In [11]:
dataset_dir = 'TG2022_Datos\Departamentos_CSV\Pre_Departamentos_personas_procesado_15.csv' #Se carga el dataset
df_d_6 = pd.read_csv(dataset_dir, sep=(',')) #Se lee el archivo csv el cual est√° separado por comas
df_d_6

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,95,1,Guaviare,24865,23221,3586,4632,5391,5289,4835,...,3365,2285,1031,2215,2024,3586,742,17715,18839,10790
1,95,15,Guaviare,4900,3748,623,856,984,1021,791,...,277,174,28,418,567,623,138,3246,3119,2145
2,95,25,Guaviare,6194,5146,714,1164,1561,1446,865,...,379,230,44,467,315,714,174,3453,4780,2933
3,95,200,Guaviare,3121,1886,320,496,620,607,511,...,161,66,13,337,609,320,154,1269,1931,1653
4,86,1,Putumayo,23870,24552,3506,3593,4316,4744,4867,...,4207,4163,1743,1437,622,3506,610,18386,21752,7674
5,86,219,Putumayo,2491,2713,405,399,430,477,451,...,291,388,81,149,75,405,70,1927,2401,806
6,86,320,Putumayo,16631,16372,2694,3094,3564,3794,3076,...,1613,1205,333,1387,332,2694,441,10102,16330,6130
7,86,568,Putumayo,28935,28320,4240,5124,5942,6471,5678,...,3313,2214,670,2302,1362,4240,855,20967,24795,10638
8,86,569,Putumayo,5769,5353,902,930,1049,1154,1072,...,308,229,96,518,216,902,188,3710,5356,1868
9,86,571,Putumayo,9178,8317,1597,1911,2338,2111,1473,...,389,321,77,904,579,1597,474,4513,8343,4165
10,86,573,Putumayo,10701,9344,1832,2395,2482,2586,1949,...,768,462,178,890,1098,1832,342,5419,8680,5604
11,86,749,Putumayo,6783,7321,941,1064,1266,1353,1305,...,941,1231,353,441,149,941,144,5149,6775,2036
12,86,755,Putumayo,2742,2830,357,407,500,553,489,...,375,344,75,141,41,357,32,2085,2679,776
13,86,757,Putumayo,7175,6879,1194,1255,1577,1640,1399,...,403,334,102,686,230,1194,250,4882,6330,2592
14,86,760,Putumayo,3340,3496,569,579,627,695,636,...,347,343,74,269,124,569,121,2037,3514,1164
15,86,865,Putumayo,13868,13587,2000,2212,2841,3323,2751,...,675,957,235,1083,371,2000,222,10259,12464,4510
16,86,885,Putumayo,11417,11213,1905,2127,2326,2630,2288,...,1029,971,266,851,431,1905,140,7647,10184,4659
17,97,1,Vaupes,14494,13215,2232,5027,4678,3639,2238,...,852,797,325,1151,957,2232,599,3397,12740,10973
18,97,161,Vaupes,1530,1297,236,530,534,416,223,...,37,33,4,164,170,236,43,195,1289,1300
19,97,511,Vaupes,2090,1866,421,752,759,569,330,...,8,6,1,415,238,421,123,33,1880,1920
20,97,666,Vaupes,1046,964,200,348,357,282,157,...,31,18,6,66,230,200,115,96,947,852
21,97,777,Vaupes,239,193,53,63,61,39,48,...,0,1,0,35,30,53,19,19,278,116
22,97,889,Vaupes,394,362,38,160,204,140,37,...,5,3,0,17,43,38,33,27,262,434
23,99,1,Vichada,10422,9366,2099,2052,2008,2037,2018,...,1322,1032,380,1927,767,2099,298,5712,8894,4884
24,99,524,Vichada,5171,4519,1005,1103,1152,1125,801,...,393,272,83,699,265,1005,102,2341,4446,2801
25,99,624,Vichada,2118,1908,376,485,535,427,346,...,126,145,34,267,44,376,45,981,1847,1153
26,99,773,Vichada,22983,20155,6078,6243,6193,5622,3970,...,464,301,76,3981,2581,6078,1805,3302,23009,15022

In [12]:
df_dataset=df_d_1.append(df_d_2 , ignore_index=True)
df_dataset=df_dataset.append(df_d_3 , ignore_index=True)
df_dataset=df_dataset.append(df_d_4 , ignore_index=True)
df_dataset=df_dataset.append(df_d_5 , ignore_index=True)
df_dataset=df_dataset.append(df_d_6 , ignore_index=True)
df_agrup_pers = df_dataset
#print(np.shape(df_dataset['U_MPIO']))
print(np.shape(df_dataset['U_MPIO'].unique()))
df_dataset

(581,)

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,19,1,Cauca,133282,143988,17049,18044,19187,22270,25292,...,23666,37041,12882,6503,4941,17049,4267,114740,118992,39271
1,19,22,Cauca,8279,8244,1075,1227,1421,1562,1456,...,215,225,60,1493,86,1075,145,4497,9579,2302
2,19,50,Cauca,10513,9623,1475,1811,1869,2021,1924,...,213,267,77,1368,340,1475,214,7867,8558,3497
3,19,75,Cauca,9513,9397,1341,1420,1796,1767,1711,...,406,274,90,1258,140,1341,272,6933,8940,2765
4,19,100,Cauca,18234,17603,2152,2535,2848,3116,3034,...,645,695,240,2369,188,2152,318,12609,18015,4895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,97,889,Vaupes,394,362,38,160,204,140,37,...,5,3,0,17,43,38,33,27,262,434
1118,99,1,Vichada,10422,9366,2099,2052,2008,2037,2018,...,1322,1032,380,1927,767,2099,298,5712,8894,4884
1119,99,524,Vichada,5171,4519,1005,1103,1152,1125,801,...,393,272,83,699,265,1005,102,2341,4446,2801
1120,99,624,Vichada,2118,1908,376,485,535,427,346,...,126,145,34,267,44,376,45,981,1847,1153
1121,99,773,Vichada,22983,20155,6078,6243,6193,5622,3970,...,464,301,76,3981,2581,6078,1805,3302,23009,15022

In [13]:
#El prop√≥sito de las siguientes l√≠neas, es revisar cu√°ntos municipios hay.
df_agrup_pers = df_dataset.drop_duplicates(subset=['U_DPTO','U_MPIO'],keep='last', inplace=False) #Se borran todas las filas
#En las cuales los municipios est√°n duplicados
df_agrup_pers.reset_index(drop=True, inplace=True)#Se reinicia el index, con el fin de que el n√∫mero de cada fila quede ordenado

df_agrup_pers#Se imprime el dataset

,U_DPTO,U_MPIO,Nom_DPTO,Per_Hombre,Per_Mujer,Per_edad_0 a 4,Per_edad_5 a 9,Per_edad_10 a 14,Per_edad_15 a 19,Per_edad_20 a 24,...,Tecnica_Profesional,Universitario,Posgrado,Ninguno,No_inf_escolaridad,No Aplica P_NIVEL_ANOSR,No informa ingresos,Recibe ingresos,No recibe ingresos,No Aplica ingresos
0,19,1,Cauca,133282,143988,17049,18044,19187,22270,25292,...,23666,37041,12882,6503,4941,17049,4267,114740,118992,39271
1,19,22,Cauca,8279,8244,1075,1227,1421,1562,1456,...,215,225,60,1493,86,1075,145,4497,9579,2302
2,19,50,Cauca,10513,9623,1475,1811,1869,2021,1924,...,213,267,77,1368,340,1475,214,7867,8558,3497
3,19,75,Cauca,9513,9397,1341,1420,1796,1767,1711,...,406,274,90,1258,140,1341,272,6933,8940,2765
4,19,100,Cauca,18234,17603,2152,2535,2848,3116,3034,...,645,695,240,2369,188,2152,318,12609,18015,4895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1117,97,889,Vaupes,394,362,38,160,204,140,37,...,5,3,0,17,43,38,33,27,262,434
1118,99,1,Vichada,10422,9366,2099,2052,2008,2037,2018,...,1322,1032,380,1927,767,2099,298,5712,8894,4884
1119,99,524,Vichada,5171,4519,1005,1103,1152,1125,801,...,393,272,83,699,265,1005,102,2341,4446,2801
1120,99,624,Vichada,2118,1908,376,485,535,427,346,...,126,145,34,267,44,376,45,981,1847,1153
1121,99,773,Vichada,22983,20155,6078,6243,6193,5622,3970,...,464,301,76,3981,2581,6078,1805,3302,23009,15022

In [14]:
export_dir = 'TG2022_Datos/Departamentos_CSV/Pre_Departamentos_per_unido.csv'
df_agrup_pers.to_csv(export_dir, index=False, header=True)